/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepapersRouteImport } from './routes/whitepapers'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BookRouteImport } from './routes/book'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AiGovernanceRouteImport } from './routes/ai-governance'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions_.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies_.$slug'

const WhitepapersRoute = WhitepapersRouteImport.update({
  id: '/whitepapers',
  path: '/whitepapers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGovernanceRoute = AiGovernanceRouteImport.update({
  id: '/ai-governance',
  path: '/ai-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions_/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies_/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-governance': typeof AiGovernanceRoute
  '/assessment': typeof AssessmentRoute
  '/book': typeof BookRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/marketplace': typeof MarketplaceRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/product': typeof ProductRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/status': typeof StatusRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/whitepapers': typeof WhitepapersRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-governance': typeof AiGovernanceRoute
  '/assessment': typeof AssessmentRoute
  '/book': typeof BookRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/marketplace': typeof MarketplaceRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/product': typeof ProductRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/status': typeof StatusRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/whitepapers': typeof WhitepapersRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-governance': typeof AiGovernanceRoute
  '/assessment': typeof AssessmentRoute
  '/book': typeof BookRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/marketplace': typeof MarketplaceRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/product': typeof ProductRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/status': typeof StatusRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/whitepapers': typeof WhitepapersRoute
  '/case-studies_/$slug': typeof CaseStudiesSlugRoute
  '/solutions_/$slug': typeof SolutionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-governance'
    | '/assessment'
    | '/book'
    | '/careers'
    | '/case-studies'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/demo'
    | '/diagnostics'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/marketplace'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/procurement'
    | '/product'
    | '/roi-calculator'
    | '/security'
    | '/sitemap.xml'
    | '/solutions'
    | '/status'
    | '/team'
    | '/terms'
    | '/whitepapers'
    | '/case-studies/$slug'
    | '/solutions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-governance'
    | '/assessment'
    | '/book'
    | '/careers'
    | '/case-studies'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/demo'
    | '/diagnostics'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/marketplace'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/procurement'
    | '/product'
    | '/roi-calculator'
    | '/security'
    | '/sitemap.xml'
    | '/solutions'
    | '/status'
    | '/team'
    | '/terms'
    | '/whitepapers'
    | '/case-studies/$slug'
    | '/solutions/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-governance'
    | '/assessment'
    | '/book'
    | '/careers'
    | '/case-studies'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/demo'
    | '/diagnostics'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/marketplace'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/procurement'
    | '/product'
    | '/roi-calculator'
    | '/security'
    | '/sitemap.xml'
    | '/solutions'
    | '/status'
    | '/team'
    | '/terms'
    | '/whitepapers'
    | '/case-studies_/$slug'
    | '/solutions_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiGovernanceRoute: typeof AiGovernanceRoute
  AssessmentRoute: typeof AssessmentRoute
  BookRoute: typeof BookRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ChangelogRoute: typeof ChangelogRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PilotRoute: typeof PilotRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcurementRoute: typeof ProcurementRoute
  ProductRoute: typeof ProductRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  StatusRoute: typeof StatusRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  WhitepapersRoute: typeof WhitepapersRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepapers': {
      id: '/whitepapers'
      path: '/whitepapers'
      fullPath: '/whitepapers'
      preLoaderRoute: typeof WhitepapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-governance': {
      id: '/ai-governance'
      path: '/ai-governance'
      fullPath: '/ai-governance'
      preLoaderRoute: typeof AiGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/$slug': {
      id: '/solutions_/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies_/$slug': {
      id: '/case-studies_/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiGovernanceRoute: AiGovernanceRoute,
  AssessmentRoute: AssessmentRoute,
  BookRoute: BookRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ChangelogRoute: ChangelogRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRoute,
  MarketplaceRoute: MarketplaceRoute,
  PilotRoute: PilotRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProcurementRoute: ProcurementRoute,
  ProductRoute: ProductRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  StatusRoute: StatusRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  WhitepapersRoute: WhitepapersRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
